<?php
namespace App\Enums;

final class RealizationStatus {
    CONST DRAFT = 'DRAFT';
    CONST WAITING_APPROVAL_BU = 'WAITING APPROVAL BU';
    CONST WAITING_APPROVAL_FINANCE = 'WAITING APPROVAL FINANCE';
    CONST APPROVED_BY_FINANCE = 'APPROVED BY FINANCE';
    CONST ARCHIVED = 'ARCHIVED';
    CONST REJECTED = 'REJECTED';

    CONST LIST = [
        'DRAFT' => 'DRAFT',
        'WAITING APPROVAL BU' => 'WAITING APPROVAL BU',
        'WAITING APPROVAL FINANCE' => 'WAITING APPROVAL FINANCE',
        'APPROVED BY FINANCE' => 'APPROVED BY FINANCE',
        'ARCHIVED' => 'ARCHIVED',
        'REJECTED' => 'REJECTED'
    ];
}
?>